# docker-compose.yml to taki przepis na uruchomienie kontenera

# wersja składni dla docker compose - juz si enie pisze tego
#version: 0.0.1

# sekcja z usługami, kontenerami do uruchomienia
services:

  # nazwa uslugi, lokalna nazwa , etykieta
  postgres:
    # obraz bazy danych, mowi dockerowi uzyj obrazu postgresql w wersji 16
    image: postgres:16-alpine

    # ustawiam nazwe nazwa kontenera
    container_name: files-manager-postgres

    # kilka zmiennych srodowiskowych
    environment:
      POSTGRES_DB: files_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    # mapowanie portow, przez ktore mzona gadac z usluga
    # polacz port 5432 na moim komputerze z portem 5432 wewnatrz kontenera
    ports:
      - "5432:5432"

    # miejsce gdzie pliki beda przechowywane
    # miejsce na trwale dane, bez tego za kazdym razem nowa baza
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # nazwa udlugi, moja nazwa
  pgadmin:

    # obraz z DockerHub
    image: dpage/pgadmin4

    # zmienne srodowiskowe
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password

    # mapowanie portow
    ports:
      # 5050 moj port na kompie, port wewnatrz kontenera
      # port 5050 na moim komputerze idzie na port 80 (domyslny pgAdmin nasluchuje na tym)
      - "5050:80"

    # w jakiej kolejnosci kontenery maja sie uruchamiac
    depends_on:
      - postgres

# tutaj nazywam wlasne wolumeny czyli magazyny na trzymanie danych
volumes:
  postgres_data: